### ISSUE TITLE
Convert to Lerna Monorepo

### ISSUE THREAD

**Issue by bonham000** [tenx-tech/stargazer#7]
This is currently a monorepo project with three sub modules: the app, client, and server packages.

We could probably convert it to a Lerna project to improve organization and dependency management.

Reference: https://github.com/lerna/lerna.

**Comment by sibelius** [comment]
use yarn workspaces

check https://github.com/entria/entria-fullstack
and https://github.com/devhubapp/devhub

**Comment by AudyOdi** [comment]
Hi there,

Thank you for having interest in the Stargazer project. Unfortunately, we couldn’t maintain the project anymore as we have shifted our tech stack and we don’t have the resources for the task. For any further developments, please feel free to fork the repo and create your own version of Stargazer.

Once again, thank you for the interest in this project. Feel free to reach out to the organization for any questions.
