### ISSUE TITLE
get route config directly from react-navigation?

### ISSUE THREAD

**Issue by sibelius** [tenx-tech/stargazer#9]
I think react-navigation is the most popular navigation solution out there

so we should provide an easy way to just use the route config from react navigation

**Comment by AudyOdi** [comment]
Hi there,

Thank you for having interest in the Stargazer project. Unfortunately, we couldn’t maintain the project anymore as we have shifted our tech stack and we don’t have the resources for the task. For any further developments, please feel free to fork the repo and create your own version of Stargazer.

Once again, thank you for the interest in this project. Feel free to reach out to the organization for any questions.
